// <auto-generated />
using System;
using EMIT_EDT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMIT_EDT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514113722_AjoutDemandeEtudiantAdmin")]
    partial class AjoutDemandeEtudiantAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMIT_EDT.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_admin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email_admin");

                    b.Property<string>("Fonction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fonction_admin");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom_admin");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pwd_admin");

                    b.HasKey("Id");

                    b.ToTable("ADMIN");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Avoir", b =>
                {
                    b.Property<int>("EtudiantId")
                        .HasColumnType("int")
                        .HasColumnName("id_etu");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("int")
                        .HasColumnName("id_parcours");

                    b.HasKey("EtudiantId", "ParcoursId");

                    b.HasIndex("ParcoursId");

                    b.ToTable("AVOIR");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Batiment", b =>
                {
                    b.Property<int>("BatimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatimentId"));

                    b.Property<string>("Localisation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NombreEtages")
                        .HasColumnType("int");

                    b.HasKey("BatimentId");

                    b.ToTable("Batiments");
                });

            modelBuilder.Entity("EMIT_EDT.Models.CreneauHoraire", b =>
                {
                    b.Property<int>("CreneauHoraireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreneauHoraireId"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("Rang")
                        .HasColumnType("int");

                    b.HasKey("CreneauHoraireId");

                    b.ToTable("CreneauHoraires");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Demande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_demande");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutreDemande")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("autre_demande");

                    b.Property<string>("CodeSalle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code_salle");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description_demande");

                    b.Property<DateTime>("DureDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("dure_debut_demande");

                    b.Property<DateTime>("DureFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("dure_fin_demande");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int")
                        .HasColumnName("id_etu");

                    b.Property<int?>("SalleId")
                        .HasColumnType("int")
                        .HasColumnName("id_salle");

                    b.Property<string>("TypeDemande")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_demande");

                    b.HasKey("Id");

                    b.HasIndex("EtudiantId");

                    b.HasIndex("SalleId");

                    b.ToTable("DEMANDE");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Enseignant", b =>
                {
                    b.Property<int>("EnseignantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnseignantId"));

                    b.Property<int>("ChargeHoraire")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_professeur");

                    b.Property<int>("DureTravaille")
                        .HasColumnType("int")
                        .HasColumnName("dure_travaille_professeur");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("titre_professeur");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EnseignantId");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Equipement", b =>
                {
                    b.Property<int>("EquipementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipementId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Icone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipementId");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("EMIT_EDT.Models.EtreTraiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_suivi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("id_admin");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int")
                        .HasColumnName("id_demande");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("DemandeId");

                    b.ToTable("ETRE_TRAITER");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_etu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email_etu");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("matricule_etu");

                    b.Property<string>("MotPasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mot_passe_etu");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom_etu");

                    b.Property<string>("NumCin")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("num_cin_etu");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom_etu");

                    b.Property<bool>("StatutValide")
                        .HasColumnType("bit")
                        .HasColumnName("status_valide");

                    b.HasKey("Id");

                    b.ToTable("ETUDIANT");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Groupe", b =>
                {
                    b.Property<int>("GroupeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupeId"));

                    b.Property<int>("Effectif")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.HasKey("GroupeId");

                    b.HasIndex("PromotionId");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("CommentaireResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSignalement")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NiveauUrgence")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalleId")
                        .HasColumnType("int");

                    b.Property<string>("SignaleParId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TechnicienId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePanne")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IncidentId");

                    b.HasIndex("SalleId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("EMIT_EDT.Models.MatiereUE", b =>
                {
                    b.Property<int>("MatiereUEId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatiereUEId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SemestreId")
                        .HasColumnType("int");

                    b.Property<int>("VolumeCM")
                        .HasColumnType("int");

                    b.Property<int>("VolumeTD")
                        .HasColumnType("int");

                    b.Property<int>("VolumeTP")
                        .HasColumnType("int");

                    b.HasKey("MatiereUEId");

                    b.HasIndex("SemestreId");

                    b.ToTable("MatiereUEs");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Mention", b =>
                {
                    b.Property<int>("MentionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MentionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MentionId");

                    b.ToTable("Mentions");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinataireId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Lu")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Parcours", b =>
                {
                    b.Property<int>("ParcoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParcoursId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MentionId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ParcoursId");

                    b.HasIndex("MentionId");

                    b.ToTable("Parcours");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Effectif")
                        .HasColumnType("int");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("int");

                    b.HasKey("PromotionId");

                    b.HasIndex("ParcoursId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Salle", b =>
                {
                    b.Property<int>("SalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalleId"));

                    b.Property<int>("BatimentId")
                        .HasColumnType("int");

                    b.Property<string>("BatimentSalle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("batiment_salle");

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Etage")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PositionSalle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("position_salle");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TypeSalleId")
                        .HasColumnType("int");

                    b.HasKey("SalleId");

                    b.HasIndex("BatimentId");

                    b.HasIndex("TypeSalleId");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("EMIT_EDT.Models.SalleEquipement", b =>
                {
                    b.Property<int>("SalleId")
                        .HasColumnType("int");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("SalleId", "EquipementId");

                    b.HasIndex("EquipementId");

                    b.ToTable("SalleEquipements");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Seance", b =>
                {
                    b.Property<int>("SeanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeanceId"));

                    b.Property<string>("Couleur")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CreeParId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreneauHoraireId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebutValidite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinValidite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupeId")
                        .HasColumnType("int");

                    b.Property<int>("JourSemaine")
                        .HasColumnType("int");

                    b.Property<int>("MatiereUEId")
                        .HasColumnType("int");

                    b.Property<string>("MotifAnnulation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("SalleId")
                        .HasColumnType("int");

                    b.Property<int>("SemestreId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("SeanceId");

                    b.HasIndex("CreneauHoraireId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("MatiereUEId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("SalleId");

                    b.HasIndex("SemestreId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Semestre", b =>
                {
                    b.Property<int>("SemestreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemestreId"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("AnneeUniversitaire")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SemestreId");

                    b.ToTable("Semestres");
                });

            modelBuilder.Entity("EMIT_EDT.Models.TypeSalle", b =>
                {
                    b.Property<int>("TypeSalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeSalleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeSalleId");

                    b.ToTable("TypeSalles");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Utilisateur", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Matricule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EnseignantMatiereUE", b =>
                {
                    b.Property<int>("EnseignantsEnseignantId")
                        .HasColumnType("int");

                    b.Property<int>("MatieresMatiereUEId")
                        .HasColumnType("int");

                    b.HasKey("EnseignantsEnseignantId", "MatieresMatiereUEId");

                    b.HasIndex("MatieresMatiereUEId");

                    b.ToTable("MatiereEnseignants", (string)null);
                });

            modelBuilder.Entity("MatiereUEParcours", b =>
                {
                    b.Property<int>("MatieresMatiereUEId")
                        .HasColumnType("int");

                    b.Property<int>("ParcoursId")
                        .HasColumnType("int");

                    b.HasKey("MatieresMatiereUEId", "ParcoursId");

                    b.HasIndex("ParcoursId");

                    b.ToTable("MatiereParcours", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EMIT_EDT.Models.Avoir", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Etudiant", "Etudiant")
                        .WithMany("Avoirs")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Parcours", "Parcours")
                        .WithMany()
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Demande", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Etudiant", "Etudiant")
                        .WithMany("Demandes")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Etudiant");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Enseignant", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Utilisateur", "Utilisateur")
                        .WithOne("Enseignant")
                        .HasForeignKey("EMIT_EDT.Models.Enseignant", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EMIT_EDT.Models.EtreTraiter", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Admin", "Admin")
                        .WithMany("Traitements")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Demande", "Demande")
                        .WithMany("Traitements")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Groupe", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Promotion", "Promotion")
                        .WithMany("Groupes")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Incident", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("EMIT_EDT.Models.MatiereUE", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Semestre", "Semestre")
                        .WithMany()
                        .HasForeignKey("SemestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Parcours", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Mention", "Mention")
                        .WithMany("Parcours")
                        .HasForeignKey("MentionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Promotion", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Parcours", "Parcours")
                        .WithMany("Promotions")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Salle", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Batiment", "Batiment")
                        .WithMany("Salles")
                        .HasForeignKey("BatimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.TypeSalle", "TypeSalle")
                        .WithMany("Salles")
                        .HasForeignKey("TypeSalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batiment");

                    b.Navigation("TypeSalle");
                });

            modelBuilder.Entity("EMIT_EDT.Models.SalleEquipement", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Seance", b =>
                {
                    b.HasOne("EMIT_EDT.Models.CreneauHoraire", "CreneauHoraire")
                        .WithMany("Seances")
                        .HasForeignKey("CreneauHoraireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Enseignant", "Enseignant")
                        .WithMany("Seances")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Groupe", "Groupe")
                        .WithMany("Seances")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EMIT_EDT.Models.MatiereUE", "MatiereUE")
                        .WithMany("Seances")
                        .HasForeignKey("MatiereUEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Promotion", "Promotion")
                        .WithMany("Seances")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Salle", "Salle")
                        .WithMany("Seances")
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Semestre", "Semestre")
                        .WithMany("Seances")
                        .HasForeignKey("SemestreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreneauHoraire");

                    b.Navigation("Enseignant");

                    b.Navigation("Groupe");

                    b.Navigation("MatiereUE");

                    b.Navigation("Promotion");

                    b.Navigation("Salle");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("EnseignantMatiereUE", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Enseignant", null)
                        .WithMany()
                        .HasForeignKey("EnseignantsEnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.MatiereUE", null)
                        .WithMany()
                        .HasForeignKey("MatieresMatiereUEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatiereUEParcours", b =>
                {
                    b.HasOne("EMIT_EDT.Models.MatiereUE", null)
                        .WithMany()
                        .HasForeignKey("MatieresMatiereUEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Parcours", null)
                        .WithMany()
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMIT_EDT.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EMIT_EDT.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMIT_EDT.Models.Admin", b =>
                {
                    b.Navigation("Traitements");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Batiment", b =>
                {
                    b.Navigation("Salles");
                });

            modelBuilder.Entity("EMIT_EDT.Models.CreneauHoraire", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Demande", b =>
                {
                    b.Navigation("Traitements");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Enseignant", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Etudiant", b =>
                {
                    b.Navigation("Avoirs");

                    b.Navigation("Demandes");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Groupe", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EMIT_EDT.Models.MatiereUE", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Mention", b =>
                {
                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Parcours", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Promotion", b =>
                {
                    b.Navigation("Groupes");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Salle", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Semestre", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("EMIT_EDT.Models.TypeSalle", b =>
                {
                    b.Navigation("Salles");
                });

            modelBuilder.Entity("EMIT_EDT.Models.Utilisateur", b =>
                {
                    b.Navigation("Enseignant");
                });
#pragma warning restore 612, 618
        }
    }
}
